item {
  id: 1
  name: 'speedLimitUrdbl'
}

item {
  id: 2
  name: 'stop'
}
item {
  id: 3
  name: 'speedLimit25'
}

item {
  id: 4
  name: 'pedestrianCrossing'
}
item {
  id: 5
  name: 'speedLimit35'
}

item {
  id: 6
  name: 'turnLeft'
}
item {
  id: 7
  name: 'slow'
}

item {
  id: 8
  name: 'speedLimit15'
}
item {
  id: 9
  name: 'speedLimit45'
}
item {
  id: 10
  name: 'rightLaneMustTurn'
}

item {
  id: 11
  name: 'signalAhead'
}
item {
  id: 12
  name: 'keepRight'
}

item {
  id: 13
  name: 'laneEnds'
}
item {
  id: 14
  name: 'school'
}

item {
  id: 15
  name: 'merge'
}
item {
  id: 16
  name: 'addedLane'
}

item {
  id: 17
  name: 'rampSpeedAdvisory40'
}
item {
  id: 18
  name: 'rampSpeedAdvisory45'
}
item {
  id: 19
  name: 'curveRight'
}

item {
  id: 20
  name: 'speedLimit65'
}
item {
  id: 21
  name: 'truckSpeedLimit55'
}

item {
  id: 22
  name: 'thruMergeLeft'
}
item {
  id: 23
  name: 'speedLimit30'
}

item {
  id: 24
  name: 'stopAhead'
}
item {
  id: 25
  name: 'yield'
}

item {
  id: 26
  name: 'thruMergeRight'
}
item {
  id: 27
  name: 'dip'
}
item {
  id: 28
  name: 'schoolSpeedLimit25'
}

item {
  id: 29
  name: 'thruTrafficMergeLeft'
}
item {
  id: 30
  name: 'noRightTurn'
}

item {
  id: 31
  name: 'rampSpeedAdvisory35'
}
item {
  id: 32
  name: 'curveLeft'
}

item {
  id: 33
  name: 'rampSpeedAdvisory20'
}
item {
  id: 34
  name: 'noLeftTurn'
}

item {
  id: 35
  name: 'zoneAhead25'
}
item {
  id: 36
  name: 'zoneAhead45'
}
item {
  id: 37
  name: 'doNotEnter'
}

item {
  id: 38
  name: 'yieldAhead'
}
item {
  id: 39
  name: 'roundabout'
}

item {
  id: 40
  name: 'turnRight'
}
